const data = {
  products: [
    {
      name: 'Skinny Jeans',
      slug: 'skinny-jeans',
      category: 'Jeans',
      image: '/images/jeans1.jpg',
      price: '30',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Slim Jeans',
      slug: 'slim-jeans',
      category: 'Jeans',
      image: '/images/jeans2.jpg',
      price: '35',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Loose Jeans',
      slug: 'loose-jeans',
      category: 'Jeans',
      image: '/images/jeans3.jpg',
      price: '20',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Taper Jeans',
      slug: 'taper-jeans',
      category: 'Jeans',
      image: '/images/jeans4.jpg',
      price: '30',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Bootcut Jeans',
      slug: 'botcut-jeans',
      category: 'Jeans',
      image: '/images/jeans5.jpg',
      price: '30',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Relaxed Jeans',
      slug: 'relaxed-jeans',
      category: 'Jeans',
      image: '/images/jeans6.jpg',
      price: '30',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
    {
      name: 'Straight Jeans',
      slug: 'straight-jeans',
      category: 'Jeans',
      image: '/images/jeans7.jpg',
      price: '30',
      brand: 'Levis',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Branded Jeans',
    },
  ],
}

export default data
